%% interpolation test file
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Izaak\Documents\Research\H2O_TempSat.xls Worksheet:
%    Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/05/21 14:14:48

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Izaak\Documents\Research\H2O_TempSat.xls','Sheet1','A4:A24');

%% Create output variable
WaterSaturationPropertiesTemperatureTable1 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Izaak\Documents\Research\H2O_TempSat.xls Worksheet:
%    Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/05/21 14:16:14

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Izaak\Documents\Research\H2O_TempSat.xls','Sheet1','B4:B24');

%% Create output variable
VarName2 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;


%% Lagrange interpolation

x= WaterSaturationPropertiesTemperatureTable1;

y=VarName2;


T=input('Temperature(0-100 C)');

Pout=Lagint(x,y,T);

display(Pout,'Saturation Pressure using Lagrange(MPa)');


%% Newton Interpolation
 

P2out=Newint(x,y,T);

display(P2out, 'Saturation Pressure using Newton (MPa)');


